[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1voaB0hwIxIqo3KjpjiMU47AqcVoZ7gGW4j3BmxyZJjo/edit?usp=sharing"


#https://docs.google.com/spreadsheets/d/1YGh6NoBFoh7aUJ2leky5riQROAvHWsjlO_Tzx30Rj90/edit?usp=sharing
